/* Generated By:JavaCC: Do not edit this line. BayesNetParseConstants.java */
public interface BayesNetParseConstants {

  int EOF = 0;
  int NETWORK = 4;
  int BNET = 5;
  int TITLE = 6;
  int COMMENT = 7;
  int AUTHOR = 8;
  int WHOCHANGED = 9;
  int WHENCHANGED = 10;
  int VERSION = 11;
  int LOCKED = 12;
  int CONSISTENCY = 13;
  int NODE = 14;
  int FINITE = 15;
  int LINK = 16;
  int RELATION = 17;
  int NODETYPE = 18;
  int NODEKIND = 19;
  int POSX = 20;
  int POSY = 21;
  int STATES = 22;
  int VALUES = 23;
  int TABLE = 24;
  int TREE = 25;
  int CONVEXSET = 26;
  int CASE = 27;
  int DEFVALUE = 28;
  int DIRECTED = 29;
  int EVERY = 30;
  int ACTIVE = 31;
  int FUNCTION = 32;
  int RELATIONNAME = 33;
  int RELATIONKIND = 34;
  int BOOLEAN = 35;
  int TRUE = 36;
  int FALSE = 37;
  int OPEN_PAREN = 38;
  int CLOSE_PAREN = 39;
  int COMMA = 40;
  int OPEN_COR = 41;
  int CLOSE_COR = 42;
  int PARAMETER_WORD = 43;
  int WORD = 44;
  int LETTER = 45;
  int DIGIT = 46;
  int DECIMAL_LITERAL = 47;
  int INTEGER = 48;
  int FLOAT = 49;
  int EQUAL = 50;
  int STRINGDECIMAL = 51;
  int STRING = 52;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"network\"",
    "\"bnet\"",
    "\"title\"",
    "\"comment\"",
    "\"author\"",
    "\"whochanged\"",
    "\"whenchanged\"",
    "\"version\"",
    "\"locked\"",
    "\"consistency-properties\"",
    "\"node\"",
    "\"finite-states\"",
    "\"link\"",
    "\"relation\"",
    "\"type-of-variable\"",
    "\"kind-of-node\"",
    "\"pos_x\"",
    "\"pos_y\"",
    "\"states\"",
    "\"values\"",
    "\"table\"",
    "\"tree\"",
    "\"convex-set\"",
    "\"case\"",
    "\"default\"",
    "\"directed\"",
    "\"every\"",
    "\"active\"",
    "\"function\"",
    "\"name-of-relation\"",
    "\"kind-of-relation\"",
    "<BOOLEAN>",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<PARAMETER_WORD>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<INTEGER>",
    "<FLOAT>",
    "\"=\"",
    "<STRINGDECIMAL>",
    "<STRING>",
    "\"}\"",
    "\"{\"",
    "\";\"",
  };

}
