/* Generated By:JavaCC: Do not edit this line. DataBaseParseConstants.java */
public interface DataBaseParseConstants {

  int EOF = 0;
  int DATABASE = 4;
  int TITLE = 5;
  int COMMENT = 6;
  int AUTHOR = 7;
  int WHOCHANGED = 8;
  int WHENCHANGED = 9;
  int VERSION = 10;
  int LOCKED = 11;
  int CONSISTENCY = 12;
  int NODE = 13;
  int FINITE = 14;
  int NODETYPE = 15;
  int NODEKIND = 16;
  int POSX = 17;
  int POSY = 18;
  int STATES = 19;
  int VALUES = 20;
  int CASES = 21;
  int DEFVALUE = 22;
  int EVERY = 23;
  int RELATION = 24;
  int MEMORY = 25;
  int CASESNUMBER = 26;
  int BOOLEAN = 27;
  int TRUE = 28;
  int FALSE = 29;
  int OPEN_PAREN = 30;
  int CLOSE_PAREN = 31;
  int COMMA = 32;
  int OPEN_COR = 33;
  int CLOSE_COR = 34;
  int WORD = 35;
  int PARAMETER_WORD = 36;
  int LETTER = 37;
  int DIGIT = 38;
  int DECIMAL_LITERAL = 39;
  int INTEGER = 40;
  int FLOAT = 41;
  int EQUAL = 42;
  int STRINGDECIMAL = 43;
  int STRING = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"data-base\"",
    "\"title\"",
    "\"comment\"",
    "\"author\"",
    "\"whochanged\"",
    "\"whenchanged\"",
    "\"version\"",
    "\"locked\"",
    "\"consistency-properties\"",
    "\"node\"",
    "\"finite-states\"",
    "\"type-of-variable\"",
    "\"kind-of-node\"",
    "\"pos_x\"",
    "\"pos_y\"",
    "\"states\"",
    "\"values\"",
    "\"cases\"",
    "\"default\"",
    "\"every\"",
    "\"relation\"",
    "\"memory\"",
    "\"number-of-cases\"",
    "<BOOLEAN>",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<WORD>",
    "<PARAMETER_WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<INTEGER>",
    "<FLOAT>",
    "\"=\"",
    "<STRINGDECIMAL>",
    "<STRING>",
    "\"}\"",
    "\"{\"",
    "\";\"",
  };

}
