/* Generated By:JavaCC: Do not edit this line. ResultParseConstants.java */
public interface ResultParseConstants {

  int EOF = 0;
  int NODE = 4;
  int VALUES = 5;
  int EQUAL = 6;
  int TABLE = 7;
  int COMMENT = 8;
  int OPEN_PAREN = 9;
  int CLOSE_PAREN = 10;
  int COMMA = 11;
  int WORD = 12;
  int LETTER = 13;
  int DIGIT = 14;
  int DECIMAL_LITERAL = 15;
  int INTEGER = 16;
  int FLOAT = 17;
  int STRINGDECIMAL = 18;
  int STRING = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"node\"",
    "\"values\"",
    "\"=\"",
    "\"table\"",
    "\"comment\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<INTEGER>",
    "<FLOAT>",
    "<STRINGDECIMAL>",
    "<STRING>",
    "\";\"",
    "\"[\"",
    "\"]\"",
  };

}
